//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDesigner {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WidgetManual {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WidgetManual() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUIDesigner.WidgetManual", typeof(WidgetManual).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 被呼叫時所下達的命令 的當地語系化字串。
        /// </summary>
        internal static string Action01to15 {
            get {
                return ResourceManager.GetString("Action01to15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件啟動時的開場特效Frame數 的當地語系化字串。
        /// </summary>
        internal static string ActiveAniFrame {
            get {
                return ResourceManager.GetString("ActiveAniFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件透明度, 255表示不透明, 0表示全透明 的當地語系化字串。
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Button動態變化效果與最初Alpha差異 的當地語系化字串。
        /// </summary>
        internal static string AlphaPercent {
            get {
                return ResourceManager.GetString("AlphaPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一直顯示直到結束 的當地語系化字串。
        /// </summary>
        internal static string AlwaysVisible {
            get {
                return ResourceManager.GetString("AlwaysVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否是上下午模式 的當地語系化字串。
        /// </summary>
        internal static string AMPM {
            get {
                return ResourceManager.GetString("AMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件旋轉角度,若有Children,會連Children一起轉 的當地語系化字串。
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所要播放的audio檔案名稱與路徑, 支援檔案格式為mp3、wma、wav 的當地語系化字串。
        /// </summary>
        internal static string AudioFilePath {
            get {
                return ResourceManager.GetString("AudioFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前沒作用 的當地語系化字串。
        /// </summary>
        internal static string AutoSize {
            get {
                return ResourceManager.GetString("AutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前沒作用 的當地語系化字串。
        /// </summary>
        internal static string AutoSizeMode {
            get {
                return ResourceManager.GetString("AutoSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 翻頁軸心的偏移量. 單位是pixel. 的當地語系化字串。
        /// </summary>
        internal static string AxisShift {
            get {
                return ResourceManager.GetString("AxisShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與背景Alpha值 的當地語系化字串。
        /// </summary>
        internal static string BackAlpha {
            get {
                return ResourceManager.GetString("BackAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當物件帶有BackImage資料時需在此指定BackImage的資料格式. 的當地語系化字串。
        /// </summary>
        internal static string BackImagePixelFormat {
            get {
                return ResourceManager.GetString("BackImagePixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進度條的圖案 的當地語系化字串。
        /// </summary>
        internal static string BarImage {
            get {
                return ResourceManager.GetString("BarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 粗字體寬度 的當地語系化字串。
        /// </summary>
        internal static string BoldSize {
            get {
                return ResourceManager.GetString("BoldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 反彈力道的百分比, 0: 不反彈, 50: 反彈半個item的寬或高度, 100: 反彈一個item的寬或高度 的當地語系化字串。
        /// </summary>
        internal static string BounceRatio {
            get {
                return ResourceManager.GetString("BounceRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制 Non-Cycle的mode時，是否要靠側邊對齊，如果設false，則Non-Cycle mode預設以置中對齊(focus item) 的當地語系化字串。
        /// </summary>
        internal static string BoundaryAlign {
            get {
                return ResourceManager.GetString("BoundaryAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇西元日曆(AD)或中國日曆(ChineseLunar) 的當地語系化字串。
        /// </summary>
        internal static string CalendarType {
            get {
                return ResourceManager.GetString("CalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checked起來時, 字型的顏色 的當地語系化字串。
        /// </summary>
        internal static string CheckedFontColor {
            get {
                return ResourceManager.GetString("CheckedFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當ChcekBox處於選擇狀態時的Image資料 的當地語系化字串。
        /// </summary>
        internal static string CheckedImage {
            get {
                return ResourceManager.GetString("CheckedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 製作閃爍的冒號用. 指向冒號文字, 可讓冒號閃爍 的當地語系化字串。
        /// </summary>
        internal static string ColonTarget {
            get {
                return ResourceManager.GetString("ColonTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支援顏色變換的動態過場效果 的當地語系化字串。
        /// </summary>
        internal static string ColorAnimation {
            get {
                return ResourceManager.GetString("ColorAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image的資料要用壓縮格式儲存或原始資料儲存. 當選擇True時, 資料檔較小, 記憶空間也比較節省, 一般都是設定為True, 當選擇False時, 資料檔較大, 但須解壓縮才顯示, 會有一些時間延遲, 對於畫面顯示及時要求時, 再使用此方式. 的當地語系化字串。
        /// </summary>
        internal static string Compress {
            get {
                return ResourceManager.GetString("Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在show JPEG圖片時, 若JPEG在同比例時長或寬超出Widget的大小, 超出的部分會被截掉. 此功能尚未實作. 的當地語系化字串。
        /// </summary>
        internal static string CutByRectange {
            get {
                return ResourceManager.GetString("CutByRectange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否要循環操作 的當地語系化字串。
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 製做最後一個物件到第一個物件的動畫，以達到一個循環 的當地語系化字串。
        /// </summary>
        internal static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統初始顯示的日期, 0代表今日 的當地語系化字串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示日期的Text物件 的當地語系化字串。
        /// </summary>
        internal static string DayTarget {
            get {
                return ResourceManager.GetString("DayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每一個frame顯示延遲時間 的當地語系化字串。
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示日期的Text物件 的當地語系化字串。
        /// </summary>
        internal static string DigitalClockDayTarget {
            get {
                return ResourceManager.GetString("DigitalClockDayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示小時的Text物件 的當地語系化字串。
        /// </summary>
        internal static string DigitalClockHourTarget {
            get {
                return ResourceManager.GetString("DigitalClockHourTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示分鐘的Text物件 的當地語系化字串。
        /// </summary>
        internal static string DigitalClockMinuteTarget {
            get {
                return ResourceManager.GetString("DigitalClockMinuteTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示秒的Text物件 的當地語系化字串。
        /// </summary>
        internal static string DigitalClockSecondTarget {
            get {
                return ResourceManager.GetString("DigitalClockSecondTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拖拉物件的功能 的當地語系化字串。
        /// </summary>
        internal static string Draggable {
            get {
                return ResourceManager.GetString("Draggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 播放投影片效果 的當地語系化字串。
        /// </summary>
        internal static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 翻頁立體的效果. 值在1-4之間. 越低立體效果越高. 的當地語系化字串。
        /// </summary>
        internal static string EffectRatio {
            get {
                return ResourceManager.GetString("EffectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show/Hide的effect要花幾個frames播完 的當地語系化字串。
        /// </summary>
        internal static string EffectSteps {
            get {
                return ResourceManager.GetString("EffectSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部的items是否都可以對touch作反應. False時只有中間的item才能對touch作反應 的當地語系化字串。
        /// </summary>
        internal static string EnableAllItems {
            get {
                return ResourceManager.GetString("EnableAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件結束的角度 的當地語系化字串。
        /// </summary>
        internal static string EndAngle {
            get {
                return ResourceManager.GetString("EndAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 過濾file副檔名 的當地語系化字串。
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生額外的itu儲存物件資料, 當要顯示時才從額外的itu中讀出, 以減小主要的itu大小, 使開機速度變快,External的widget帶有圖片時, 會將圖片資料存在同一layer的額外檔案裡 的當地語系化字串。
        /// </summary>
        internal static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name指定圖片(.PNG or .JPG)相關路徑, 由程式發出ITU_EVENT_LOAD_IMAGE event時統一讀入圖片檔案 的當地語系化字串。
        /// </summary>
        internal static string ExternalImage {
            get {
                return ResourceManager.GetString("ExternalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 縮放百分比 的當地語系化字串。
        /// </summary>
        internal static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同Name, 用於ExternalImage開啟時指定相關路徑用. 但因為Name會檢查是否有其它Widget有相同的Name, 若有需要不同的Icon需要Load同一張檔案時, 可在這裡指定. 的當地語系化字串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在show JPEG圖片時, 若JPEG在同比例時長或寬小於Widget的大小, 小於的部分會被填黑. 的當地語系化字串。
        /// </summary>
        internal static string FitToRectange {
            get {
                return ResourceManager.GetString("FitToRectange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當ChcekBox處於Focus而且是選擇狀態時的Image資料 的當地語系化字串。
        /// </summary>
        internal static string FocusCheckedImage {
            get {
                return ResourceManager.GetString("FocusCheckedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當物件處於Focus狀態時的顏色 的當地語系化字串。
        /// </summary>
        internal static string FocusColor {
            get {
                return ResourceManager.GetString("FocusColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當物件處於Focus狀態時的文字顏色 的當地語系化字串。
        /// </summary>
        internal static string FocusFontColor {
            get {
                return ResourceManager.GetString("FocusFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當前Focus項目的字體高度 的當地語系化字串。
        /// </summary>
        internal static string FocusFontHeight {
            get {
                return ResourceManager.GetString("FocusFontHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處於Focus時的Image資料 的當地語系化字串。
        /// </summary>
        internal static string FocusImage {
            get {
                return ResourceManager.GetString("FocusImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當Item被選中時, 該Item的內容會被解譯成數字, 決定show第幾個FocusImage 的當地語系化字串。
        /// </summary>
        internal static string FocusImage0to15 {
            get {
                return ResourceManager.GetString("FocusImage0to15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初始顯示時中央位置的物件編號 的當地語系化字串。
        /// </summary>
        internal static string FocusIndex {
            get {
                return ResourceManager.GetString("FocusIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 多字型時, 指定要使用哪個字型 的當地語系化字串。
        /// </summary>
        internal static string FontIndex {
            get {
                return ResourceManager.GetString("FontIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否將Focus項目字體等寬高放大 (預設否，表示只拉長高度至FocusFontHeight) 的當地語系化字串。
        /// </summary>
        internal static string FontSquare {
            get {
                return ResourceManager.GetString("FontSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期五欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string FridayTarget {
            get {
                return ResourceManager.GetString("FridayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在製作動態排列icon的功能時, 每個icon之間的間隔. Layout需設成Grid. 請參考project\dynamic_ui 的當地語系化字串。
        /// </summary>
        internal static string Gap {
            get {
                return ResourceManager.GetString("Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 漸層顏色 的當地語系化字串。
        /// </summary>
        internal static string GradientColor {
            get {
                return ResourceManager.GetString("GradientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 漸層模式 的當地語系化字串。
        /// </summary>
        internal static string GradientMode {
            get {
                return ResourceManager.GetString("GradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可接收長按 的當地語系化字串。
        /// </summary>
        internal static string HasLongPress {
            get {
                return ResourceManager.GetString("HasLongPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 命令物件隱藏 的當地語系化字串。
        /// </summary>
        internal static string Hided {
            get {
                return ResourceManager.GetString("Hided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 widget隔多久自動消失, -1不開啟. 單位是frame 的當地語系化字串。
        /// </summary>
        internal static string HideDelay {
            get {
                return ResourceManager.GetString("HideDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隱藏時得過場效果 的當地語系化字串。
        /// </summary>
        internal static string HidingEffect {
            get {
                return ResourceManager.GetString("HidingEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示時針的Icon物件 的當地語系化字串。
        /// </summary>
        internal static string HourTarget {
            get {
                return ResourceManager.GetString("HourTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 時針Icon物件的圓心座標X 的當地語系化字串。
        /// </summary>
        internal static string HourX {
            get {
                return ResourceManager.GetString("HourX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 時針Icon物件的圓心座標Y 的當地語系化字串。
        /// </summary>
        internal static string HourY {
            get {
                return ResourceManager.GetString("HourY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當Item未被選中時, 該Item的內容會被解譯成數字, 決定show第幾個FocusImage 的當地語系化字串。
        /// </summary>
        internal static string Image0to15 {
            get {
                return ResourceManager.GetString("Image0to15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當物件帶有Image資料時需在此指定Image的資料格式. 的當地語系化字串。
        /// </summary>
        internal static string ImagePixelFormat {
            get {
                return ResourceManager.GetString("ImagePixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Button動態變化效果與最初大小差異 的當地語系化字串。
        /// </summary>
        internal static string IncreasePercent {
            get {
                return ResourceManager.GetString("IncreasePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有幾個Item要show出來 的當地語系化字串。
        /// </summary>
        internal static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每一列的初始值, 我們可利用初始值設定, 來確認圖面設計是否正確. 的當地語系化字串。
        /// </summary>
        internal static string Items1to7 {
            get {
                return ResourceManager.GetString("Items1to7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 縮放幾次 的當地語系化字串。
        /// </summary>
        internal static string Iterator {
            get {
                return ResourceManager.GetString("Iterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否可以透過手指按下指定的位置, 直接跳到指定的進度 的當地語系化字串。
        /// </summary>
        internal static string Jumpable {
            get {
                return ResourceManager.GetString("Jumpable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在程式未下ITU_EVENT_LANGUAGE event之前, default show哪個frame 的當地語系化字串。
        /// </summary>
        internal static string LanguageIndex {
            get {
                return ResourceManager.GetString("LanguageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 若為Grid則會自動隊齊 的當地語系化字串。
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ScrollBar指定的page數量初始值, 這部份給default值即可 的當地語系化字串。
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字框高度 的當地語系化字串。
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最大值 的當地語系化字串。
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示年的最大值 的當地語系化字串。
        /// </summary>
        internal static string MaximumYear {
            get {
                return ResourceManager.GetString("MaximumYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最大值 的當地語系化字串。
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最小值 的當地語系化字串。
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示年的最小值 的當地語系化字串。
        /// </summary>
        internal static string MinimumYear {
            get {
                return ResourceManager.GetString("MinimumYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當手指在MinRadius內作動作時, 不會影響Meter的動作 的當地語系化字串。
        /// </summary>
        internal static string MinRadius {
            get {
                return ResourceManager.GetString("MinRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示分針的Icon物件 的當地語系化字串。
        /// </summary>
        internal static string MinuteTarget {
            get {
                return ResourceManager.GetString("MinuteTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分針Icon物件的圓心座標X 的當地語系化字串。
        /// </summary>
        internal static string MinuteX {
            get {
                return ResourceManager.GetString("MinuteX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分針Icon物件的圓心座標Y 的當地語系化字串。
        /// </summary>
        internal static string MinuteY {
            get {
                return ResourceManager.GetString("MinuteY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期一欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string MondayTarget {
            get {
                return ResourceManager.GetString("MondayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統初始顯示的月份, 0代表今日月份 的當地語系化字串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示月份的Text物件 的當地語系化字串。
        /// </summary>
        internal static string MonthTarget {
            get {
                return ResourceManager.GetString("MonthTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支援移動的動態過場效果 的當地語系化字串。
        /// </summary>
        internal static string MoveAnimation {
            get {
                return ResourceManager.GetString("MoveAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移動方式. 可以是線性速度移動或是加減速效果的移動 的當地語系化字串。
        /// </summary>
        internal static string MoveType {
            get {
                return ResourceManager.GetString("MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件名稱 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移動方向 的當地語系化字串。
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件之間可重疊的pixel數 的當地語系化字串。
        /// </summary>
        internal static string Overlapsize {
            get {
                return ResourceManager.GetString("Overlapsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PageCount代表總共有幾頁的資料, 系統會將此數字轉成字串, 使用者可在此欄位選擇一Text物件, 即可將其顯示出來. 的當地語系化字串。
        /// </summary>
        internal static string PageCountTarget {
            get {
                return ResourceManager.GetString("PageCountTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PageIndex代表目前顯示的是第幾頁的資料, 系統會將此數字轉成字串, 使用者可在此欄位選擇一Text物件, 即可將其顯示出來. 的當地語系化字串。
        /// </summary>
        internal static string PageIndexTarget {
            get {
                return ResourceManager.GetString("PageIndexTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所要列出的檔案的目錄名稱 的當地語系化字串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 畫筆顏色 的當地語系化字串。
        /// </summary>
        internal static string PenColor {
            get {
                return ResourceManager.GetString("PenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示數值的Text物件 的當地語系化字串。
        /// </summary>
        internal static string PercentTarget {
            get {
                return ResourceManager.GetString("PercentTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當物件帶有Image資料時需在此指定image的資料格式. 的當地語系化字串。
        /// </summary>
        internal static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件初始在Play狀態 的當地語系化字串。
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各點的位置 的當地語系化字串。
        /// </summary>
        internal static string Point00to31 {
            get {
                return ResourceManager.GetString("Point00to31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點的總數量 的當地語系化字串。
        /// </summary>
        internal static string PointCount {
            get {
                return ResourceManager.GetString("PointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示Meter指針的Icon物件 的當地語系化字串。
        /// </summary>
        internal static string PointerTarget {
            get {
                return ResourceManager.GetString("PointerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Meter指針Icon物件的圓心座標X 的當地語系化字串。
        /// </summary>
        internal static string PointerX {
            get {
                return ResourceManager.GetString("PointerX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Meter指針Icon物件的圓心座標Y 的當地語系化字串。
        /// </summary>
        internal static string PointerY {
            get {
                return ResourceManager.GetString("PointerY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ScrollBar指定的項目位置初始page 的當地語系化字串。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當按下物件時的背景Image資料 的當地語系化字串。
        /// </summary>
        internal static string PressImage {
            get {
                return ResourceManager.GetString("PressImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繪圖筆的初始預設筆寬 的當地語系化字串。
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟後, 當show某個指定的frame時, 前面全部的frame也會show出來. 主要用來實作格狀的進度條用 的當地語系化字串。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一個長條的Icon物件, 長度是所要畫圓的半徑, 寬度介於1~10之間, 取決於累進一單位的數值時是否會將一單位的弧形填滿. 的當地語系化字串。
        /// </summary>
        internal static string ProgressTarget {
            get {
                return ResourceManager.GetString("ProgressTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 製作RippleMap時取樣的半徑 的當地語系化字串。
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ripple擴散時影響的範圍 的當地語系化字串。
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Flip2效果中, 指定不同分頁Y軸的中間值百分比. 越低越靠近上面. 的當地語系化字串。
        /// </summary>
        internal static string RatioFlip2 {
            get {
                return ResourceManager.GetString("RatioFlip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表示此項目已讀過的文字顏色. 需用ituScrollTextSetAsRead()來指示已讀 的當地語系化字串。
        /// </summary>
        internal static string ReadFontColor {
            get {
                return ResourceManager.GetString("ReadFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重複播放 的當地語系化字串。
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定是否在MouseUp時才動作, 主要避免有滑動手勢時的誤動作 的當地語系化字串。
        /// </summary>
        internal static string ResponseToUpKey {
            get {
                return ResourceManager.GetString("ResponseToUpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支援旋轉的動態過場效果 的當地語系化字串。
        /// </summary>
        internal static string RotateAnimation {
            get {
                return ResourceManager.GetString("RotateAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期六欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string SaturdayTarget {
            get {
                return ResourceManager.GetString("SaturdayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支援縮放的動態過場效果 的當地語系化字串。
        /// </summary>
        internal static string ScaleAnimation {
            get {
                return ResourceManager.GetString("ScaleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 縮放時是否是對著中心點縮放 的當地語系化字串。
        /// </summary>
        internal static string ScaleOnCenter {
            get {
                return ResourceManager.GetString("ScaleOnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當字串長度超過物件寬度時, 字串顯示會自動向左捲動, 以顯示接下來的字串, 此參數的目的是控制捲動的速度, 移動速度為33ms乘上參數值 的當地語系化字串。
        /// </summary>
        internal static string ScrollDelay {
            get {
                return ResourceManager.GetString("ScrollDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示秒針的Icon物件 的當地語系化字串。
        /// </summary>
        internal static string SecondTarget {
            get {
                return ResourceManager.GetString("SecondTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 秒針Icon物件的圓心座標X 的當地語系化字串。
        /// </summary>
        internal static string SecondX {
            get {
                return ResourceManager.GetString("SecondX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 秒針Icon物件的圓心座標Y 的當地語系化字串。
        /// </summary>
        internal static string SecondY {
            get {
                return ResourceManager.GetString("SecondY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在文字輸入點是否顯示輸入提示符號 的當地語系化字串。
        /// </summary>
        internal static string ShowCursor {
            get {
                return ResourceManager.GetString("ShowCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 widget隔多久自動出現, -1不開啟. 單位是frame 的當地語系化字串。
        /// </summary>
        internal static string ShowDelay {
            get {
                return ResourceManager.GetString("ShowDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示時的過場效果 的當地語系化字串。
        /// </summary>
        internal static string ShowingEffect {
            get {
                return ResourceManager.GetString("ShowingEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一次slide可移動的最大item數 的當地語系化字串。
        /// </summary>
        internal static string SlideMaxCount {
            get {
                return ResourceManager.GetString("SlideMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 滑動頁數 的當地語系化字串。
        /// </summary>
        internal static string SlidePage {
            get {
                return ResourceManager.GetString("SlidePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件開始的角度 的當地語系化字串。
        /// </summary>
        internal static string StartAngle {
            get {
                return ResourceManager.GetString("StartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 背景是否是靜態物件 的當地語系化字串。
        /// </summary>
        internal static string Static {
            get {
                return ResourceManager.GetString("Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能保留 的當地語系化字串。
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否可在任意位置停止 的當地語系化字串。
        /// </summary>
        internal static string StopAnywhere {
            get {
                return ResourceManager.GetString("StopAnywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當字串長度超過物件寬度時, 字串顯示會自動向左捲動, 以顯示接下來的字串, 當左捲到最後時會停頓此參數值乘上33ms時間在右捲回去 的當地語系化字串。
        /// </summary>
        internal static string StopDelay {
            get {
                return ResourceManager.GetString("StopDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片延展至物件大小 的當地語系化字串。
        /// </summary>
        internal static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期日欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string SundayTarget {
            get {
                return ResourceManager.GetString("SundayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否開啟由Touch輸入 的當地語系化字串。
        /// </summary>
        internal static string SupportTouch {
            get {
                return ResourceManager.GetString("SupportTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指向要做倒影的對象 的當地語系化字串。
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能保留 的當地語系化字串。
        /// </summary>
        internal static string Text1to7 {
            get {
                return ResourceManager.GetString("Text1to7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文字對齊位置 的當地語系化字串。
        /// </summary>
        internal static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字串顏色 的當地語系化字串。
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 按鈕文字放大比率，若小於等於0，不使用此功能，即行為效果跟原本一樣；若介於1至50之間，按下按鈕時，文字跟著放大的增加比例；舉例: 30，即按下時，按鈕文字會放大增至130% 的當地語系化字串。
        /// </summary>
        internal static string TextScaleFactor {
            get {
                return ResourceManager.GetString("TextScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期四欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string ThursdayTarget {
            get {
                return ResourceManager.GetString("ThursdayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TrackBar顯示註解的物件 的當地語系化字串。
        /// </summary>
        internal static string TipTarget {
            get {
                return ResourceManager.GetString("TipTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 動態過場效果的frame數 的當地語系化字串。
        /// </summary>
        internal static string TotalFrame {
            get {
                return ResourceManager.GetString("TotalFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否可接收touch event 的當地語系化字串。
        /// </summary>
        internal static string Touchable {
            get {
                return ResourceManager.GetString("Touchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 微調左右2邊開始拖動的部分. 主要是配合TrackBar圖資邊界不能拖動的部分 的當地語系化字串。
        /// </summary>
        internal static string TrackBarGap {
            get {
                return ResourceManager.GetString("TrackBarGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拖動時一次要移動幾個單位 的當地語系化字串。
        /// </summary>
        internal static string TrackBarStep {
            get {
                return ResourceManager.GetString("TrackBarStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TrackBar按鈕的 Button物件 的當地語系化字串。
        /// </summary>
        internal static string TrackerTarget {
            get {
                return ResourceManager.GetString("TrackerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 父物件的alpha值是否要傳遞給子物件 的當地語系化字串。
        /// </summary>
        internal static string TransferAlpha {
            get {
                return ResourceManager.GetString("TransferAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定是否是翻頁效果. 範例請參考project\test_itu\examples\transform_animation.xml 的當地語系化字串。
        /// </summary>
        internal static string TransformAnimation {
            get {
                return ResourceManager.GetString("TransformAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 翻轉效果. 需要與Animation widget配合,有turnTop, turnBottom, turnRight, turnLeft 四种形变，再依据TransformX和TransformY来设定型变程度 的當地語系化字串。
        /// </summary>
        internal static string TransformType {
            get {
                return ResourceManager.GetString("TransformType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 翻轉的X軸是原來widget寬度的多少, 單位是百分比值, 100維持不變, 50縮小一半 的當地語系化字串。
        /// </summary>
        internal static string TransformX {
            get {
                return ResourceManager.GetString("TransformX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 翻轉的Y軸是原來widget寬度的多少, 單位是百分比值, 100維持不變, 50縮小一半 的當地語系化字串。
        /// </summary>
        internal static string TransformY {
            get {
                return ResourceManager.GetString("TransformY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期二欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string TuesdayTarget {
            get {
                return ResourceManager.GetString("TuesdayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 翻頁的效果. 可參考ctrlboard 的當地語系化字串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件初始值 的當地語系化字串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示widget數值的Text物件 的當地語系化字串。
        /// </summary>
        internal static string ValueTarget {
            get {
                return ResourceManager.GetString("ValueTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 音量. 單位是百份比 的當地語系化字串。
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否開啟調整音量功能 的當地語系化字串。
        /// </summary>
        internal static string VolumeEnable {
            get {
                return ResourceManager.GetString("VolumeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示星期三欄位的ListBox物件 的當地語系化字串。
        /// </summary>
        internal static string WednesdayTarget {
            get {
                return ResourceManager.GetString("WednesdayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示週的Text物件 的當地語系化字串。
        /// </summary>
        internal static string WeekTarget {
            get {
                return ResourceManager.GetString("WeekTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統初始顯示的年份, 0代表今日年份 的當地語系化字串。
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示西元年的Text物件 的當地語系化字串。
        /// </summary>
        internal static string YearTarget {
            get {
                return ResourceManager.GetString("YearTarget", resourceCulture);
            }
        }
    }
}
