add_executable(${CMAKE_PROJECT_NAME}
    layer_main.c
    layer_more_mode.c
    layer_induction.c
    layer_induction_setting.c
    layer_set_temp.c
    layer_set_temp1.c
    layer_filter.c
    layer_emergency.c
    layer_warning.c
	layer_set_humidity.c
	layer_common_tool.c
	layer_screen_lock.c
	layer_timing.c
	layer_setting.c
	layer_examine.c
	layer_power_off.c
	layer_trial_run.c
	layer_air_flow.c
    )
